repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: ^src/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^src/.*\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        files: ^(benchmark_datasets|benchmark)/.*\.ya?ml$
      - id: end-of-file-fixer
        files: ^src/.*|\.ya?ml|\.md|\.toml$
      - id: trailing-whitespace
        files: ^src/.*|\.md$
      - id: check-added-large-files
        files: ^src/
      - id: debug-statements
        files: ^src/
